### ISSUE TITLE
Task: Build frontend and run unit tests

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication-frontend#116]
See action for altinn-access-management-frontend

https://github.com/Altinn/altinn-access-management-frontend/blob/main/.github/workflows/build-frontend.yaml

**Comment by Torgeir333** [comment]
Probably this issue needs to be clarified somewhat.

Frontend has been built, both locally, and in GitHub Action workflow,
as also has the first unit tests (i.e. Cypress component tests),
as summarised in issue #106 
which again summarises issue #29 ,
and issue #100 

Furthermore, the Frontend has been built, wrapped in a BFF dotnet app, 
and published to Azure Container App accessible on the net,
as described in issue #113 
(and possibly issue #114, which is "greek to me").
