### ISSUE TITLE
Logged in actor is not displayed in the administrate system user page

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication-frontend#262]
### Description of the bug

After login, when i chose an actor, the actor name along with the logged in person must be displayed but it just displays the chosen actor

### Steps To Reproduce

1. Go to administrate system user page
2. User is redirected to login
3. Enter the credentials and login
4. Choose the actor
5. User is redirected to administrate system user page
6. In the actor panel at the top rigt corner, only name of the chosen actor is seen. 
7. Name of the logged in person must also be displayed

**Comment by mgunnerud** [comment]
@acn-dgopa can this be closed now?

**Comment by mgunnerud** [comment]
Fixed
