### ISSUE TITLE
List of systems from the system register in adminstrate system user page does not load on landing

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication-frontend#263]
### Description of the bug

List of systems from the system register in adminstrate system user page does not load on landing. It should load on the first landing

### Steps To Reproduce

1. Go to adminstrate system user page
2. User is redirected to login
3. Enter the credentials and choose the actor
4. User is redirected to the administrate system user page
5. Click on "create system user"
6. Input fields to create a system user is displayed
7. There is a dropdown to list available systems
8. The dropdown does not load with systems, we just get error message
9. Systems must be displayed and no error message

**Comment by mgunnerud** [comment]
Fixed by https://github.com/Altinn/altinn-authentication-frontend/pull/265
