### ISSUE TITLE
BFF calls the new endpoint in authorization api to check if the user has the required rights that he is delegating to the system user ( Delegationcheck)

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication-frontend#299]
Before the user approve the creation of a system user, the BFF should check with AM if both the set of Rights are delegable by this user, and that the user has the Role "Tilgangsstyrer"
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authentication/issues/607
```

**Comment by Nyeng** [comment]
Lukker, for det kommer en ny variant av denne som gjør denne deprecated
