### ISSUE TITLE
Implement Altinn system user design of User-initiated process (v1) in frontend

### ISSUE THREAD

**Issue by MetteGrytten** [Altinn/altinn-authentication-frontend#305]
### **System user**
**As a user I would like to be able to create a new system user and administrate my existing system users in altinn.no.**

When you create a system user you need to connect the user to a system. The system vendor has in advance defined rights that are included with their system. We need to show the user which rights follows the system.

The user should also be able to add several system users, and also delete a system user.

If the system vendor adds more rights later, the user needs to get notified.

The user flow starts at Profile/Avanserte innstillinger (logged in).

The solution also has to harmonize with the [vendor initiated system user creation](https://github.com/orgs/Altinn/projects/75/views/9?pane=issue&itemId=42383486)

Overordnet beskrivelse: https://github.com/digdir/roadmap/issues/284
Fremtidig løsning for sluttbrukersystemer: https://github.com/Altinn/altinn-authentication/issues/200

-----
### **Main user flow**
Changes in screenshots may occur, for updated and more detailed sketches see [FIGMA](https://www.figma.com/file/qWEscJDVrA2gDP6oTI4Dfm/Team-Tilgangsinfo?type=design&node-id=1502%3A97989&mode=design&t=kcI40tL0pueGoMly-1)
The user flow is tested on several users, and the sketches including texts are ready to be implemented in front end.
[Usability testing documentation in Miro](https://miro.com/app/board/uXjVNjsv8uE=/?share_link_id=469377059852)

**When user first enters System user from Altinn:**
_View when user does not have any system users:_ 
<img width="439" alt="Skjermbilde 2024-04-26 kl  10 43 20" src="https://github.com/Altinn/altinn-studio/assets/144321622/c4d5dd5c-ce4d-4c14-82b8-f22483f94953">

_ View when user already has System user(s):_
- Listed by last added (or by alphabet, this one is open for discussion)
- Title "Rekneskapsprogrammet vårt" in sketch, refers to naming. The name of the system should be default, with edit possibilities
- Undertitle "Fiken" in sketch, refers to the name of the provider
<img width="443" alt="Skjermbilde 2024-04-26 kl  10 31 59" src="https://github.com/Altinn/altinn-studio/assets/144321622/6999f84f-dcb5-4671-b59e-657dde56994c">

_View when user already has System user(s) without given rights:_
<img width="437" alt="Skjermbilde 2024-04-26 kl  10 42 09" src="https://github.com/Altinn/altinn-studio/assets/144321622/907eac90-c84a-46ac-93a3-6fa4a6cb4d61">

-------
### **Main user flow: Give the system user a name and choose system from a provider** 
- The name of the system should be presented as a default with edit possibilities. 
- Combobox that shows 5 systems at a time, containing name of system, system provider and the org.number of the system provider. When typing you can minimize search result (org.number or name)

<img width="439" alt="Skjermbilde 2024-04-26 kl  10 34 32" src="https://github.com/Altinn/altinn-studio/assets/144321622/64645080-4f0d-487f-b7b4-0286a2665b6a">

<img width="436" alt="Skjermbilde 2024-04-26 kl  10 44 22" src="https://github.com/Altinn/altinn-studio/assets/144321622/41a8bcc7-019b-4e0c-b200-26d4fe6bdd32">

-------
### **Main user flow: Present included rights**
 
<img width="438" alt="Skjermbilde 2024-04-26 kl  10 45 24" src="https://github.com/Altinn/altinn-studio/assets/144321622/1b012eb7-4b7d-422d-9331-9ad2cec582c9">

-------
### **Main user flow: Confirmation created system user **
- The last created system user shows open on top, with the text "Du har nå laget denne systemtilgangen"
- Any other system users shows closed below the new one under "Tidligere opprettede systemtilganger"

<img width="436" alt="Skjermbilde 2024-04-26 kl  10 48 21" src="https://github.com/Altinn/altinn-studio/assets/144321622/9c06b57e-56a9-4dc5-9d85-114e6b689441">

-----
### **Edit mode**
With possibilities to: 
- Change name
- Delete system user

_First view:_
<img width="439" alt="Skjermbilde 2024-04-26 kl  10 26 07" src="https://github.com/Altinn/altinn-studio/assets/144321622/da82d073-cce8-4b7a-82c4-e5fa06972fa6">

_Modal if you try to delete system user:_
<img width="437" alt="Skjermbilde 2024-04-26 kl  10 26 24" src="https://github.com/Altinn/altinn-studio/assets/144321622/abc784e5-eec3-4706-8b1f-1fd925f5f84f">

-----

### **Errors**

Errors may occur if you do not have the necessary rights to delegate. 

<img width="416" alt="Skjermbilde 2024-05-03 kl  09 56 14" src="https://github.com/Altinn/altinn-studio/assets/144321622/bc563a74-2893-483b-ad31-c78a5d66c22b">

If it´s possible, it may be useful to show which right(s) missing: 

<img width="419" alt="Skjermbilde 2024-05-03 kl  09 56 21" src="https://github.com/Altinn/altinn-studio/assets/144321622/71326681-ee84-4712-aa8e-b9b5045d7f4e">

**Comment by Nyeng** [comment]
Lukkes etter refinment-prat. Kommer ny oppgave på dene til test som tar for seg ulike feilscenarioer som kommer til bruker.
